### ISSUE TITLE
Crash Android Release

### ISSUE THREAD

**Issue by ajiehatajie** [RobbyWH/react-native-zendesk-messaging#14]
Random Crash Android Release React native 71.7

**Comment by robbywh** [comment]
@ajiehatajie Can you share the error log?

**Comment by Ankur-Float** [comment]
@robbywh I am facing the same issue and here is the error:

```
* What went wrong:
Could not determine the dependencies of task ':robbywh_react-native-zendesk-messaging:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':robbywh_react-native-zendesk-messaging:debugCompileClasspath'.
   > Could not resolve zendesk.messaging:messaging-android:2.9.0.
     Required by:
         project :robbywh_react-native-zendesk-messaging
      > Could not resolve zendesk.messaging:messaging-android:2.9.0.
         > Could not get resource 'https://zendesk.jfrog.io/ui/native/repo/zendesk/messaging/messaging-android/2.9.0/messaging-android-2.9.0.pom'.
            > Could not HEAD 'https://zendesk.jfrog.io/ui/native/repo/zendesk/messaging/messaging-android/2.9.0/messaging-android-2.9.0.pom'. Received status code 403 from server: Forbidden
```

**Comment by hamedfoodready** [comment]
> @robbywh I am facing the same issue and here is the error:
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':robbywh_react-native-zendesk-messaging:compileDebugAidl'.
> > Could not resolve all task dependencies for configuration ':robbywh_react-native-zendesk-messaging:debugCompileClasspath'.
>    > Could not resolve zendesk.messaging:messaging-android:2.9.0.
>      Required by:
>          project :robbywh_react-native-zendesk-messaging
>       > Could not resolve zendesk.messaging:messaging-android:2.9.0.
>          > Could not get resource 'https://zendesk.jfrog.io/ui/native/repo/zendesk/messaging/messaging-android/2.9.0/messaging-android-2.9.0.pom'.
>             > Could not HEAD 'https://zendesk.jfrog.io/ui/native/repo/zendesk/messaging/messaging-android/2.9.0/messaging-android-2.9.0.pom'. Received status code 403 from server: Forbidden
> ```

I Have the same issue. Could not resolve zendesk.messaging:messaging-android:2.9.0
Did you find any solution for this issue?

**Comment by Ankur-Float** [comment]
@hamedfoodready I had to add below section in android -> build.gradle

```
allprojects {
    repositories {
        maven {
            url "https://zendesk.jfrog.io/artifactory/repo"
        }
    }
}
```

**Comment by robbywh** [comment]
Hello guys, I have moved to another company and I don't work with Zendesk anymore. Feel free to open the PR or tell me if you want to become a collaborator

**Comment by hamedfoodready** [comment]
> Hello guys, I have moved to another company and I don't work with Zendesk anymore. Feel free to open the PR or tell me if you want to become a collaborator

I want to become a collabrator

**Comment by Ankur-Float** [comment]
I am interested

**Comment by Ankur-Float** [comment]
> Hello guys, I have moved to another company and I don't work with Zendesk anymore. Feel free to open the PR or tell me if you want to become a collaborator

I am interested @robbywh

**Comment by robbywh** [comment]
Hello @hamedfoodready @Ankur-Float,

Thank you for your interest.
I have invited you to become a collaborator for this repository
