### ISSUE TITLE
How to do authorization

### ISSUE THREAD

**Issue by techhoney15** [RobbyWH/react-native-zendesk-messaging#15]
Hello

When we use Zendesk and log in with one account and chat and log out. If we log in with other credentials then the same chat appears. How do initialize with one user as per login credentials? So that different chats will appear for different accounts.

Thank you.

**Comment by disrae** [comment]
This is a known issue described on the zendesk sdk website, so it's on their end, but I think uninstalling the app and reinstalling will clear the stored chat. 🤷‍♂️
