### ISSUE TITLE
Cannot find module '@flashcoffee/react-native-zendesk-messaging' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by alxhghs** [RobbyWH/react-native-zendesk-messaging#7]
This package looks really awesome! Hoping to get it working for my app.

I'm having an issue where the following message is logged after installing this package.

```
Cannot find module '@flashcoffee/react-native-zendesk-messaging' or its corresponding type declarations.ts
```

I've tried this in a large expo app, a bare bones react native app and a web app. Any idea what the issue might be?

I created a repo to reproduce the issue:

https://github.com/alxhghs/react-native-messaging-test

**Comment by elabayoub** [comment]
Hello, i had same issue, i've downgraded to node 14.17.0 and re-run `npm i`

**Comment by alxhghs** [comment]
Downgrading node is less than ideal but that's a great lead

**Comment by robbywh** [comment]
Hello guys, sorry for the delay. I will continue to maintain this package. I will let you know, If I have fixed the issue

**Comment by robbywh** [comment]
Hello @alxhghs @elabayoub.  Can you try the latest version using this: `yarn add @robbywh/react-native-zendesk-messaging`?
