### ISSUE TITLE
'ZendeskUser' could not be found

### ISSUE THREAD

**Issue by stefandbd** [RobbyWH/react-native-zendesk-messaging#8]
For the latest version (1.0.4), while building the app, xCode crashes with an error from ZendeskMessaging.swift:

`'ZendeskUser' could not be found`

Previous steps:
yarn
cd ios && pod install

RN version: 0.70.3

**Comment by elabayoub** [comment]
Same issue.

**Comment by elabayoub** [comment]
@stefandbd not the best solution but try to downgrade node to 14.17.0 and re-run `npm i` as a workaround.
Otherwise switch to leegeunhyeok's repo (https://github.com/leegeunhyeok/react-native-zendesk-messaging)

**Comment by dheeyi** [comment]
@stefandbd Could you find the solution for this error?

**Comment by alxhghs** [comment]
> @stefandbd not the best solution but try to downgrade node to 14.17.0 and re-run `npm i` as a workaround.
> 
> Otherwise switch to leegeunhyeok's repo (https://github.com/leegeunhyeok/react-native-zendesk-messaging)

That version of zendesk messaging looks like it has a lot of cool features. Any reason we should be using this package or the other one?

**Comment by DineshRajput21** [comment]
> https://github.com/leegeunhyeok/react-native-zendesk-messaging

It's not working in android at all

**Comment by robbywh** [comment]
Hello guys, sorry for the delay. I will continue to maintain this package. I will let you know, If I have fixed the issue

**Comment by robbywh** [comment]
Hello @stefandbd  @DineshRajput21 @elabayoub @dheeyi @alxhghs , I have fixed this issue and updated the example code using the newer react-native version. You can try the latest version using this: `yarn add @robbywh/react-native-zendesk-messaging`
