### ISSUE TITLE
No such module 'ZendeskUser'

### ISSUE THREAD

**Issue by fernando-ropero-akimad** [RobbyWH/react-native-zendesk-messaging#9]
ZendeskMessagin.swift

`import ZendeskUser`

"@flashcoffee/react-native-zendesk-messaging": "^1.0.4",

**Comment by robbywh** [comment]
Hello @fernando-ropero-akimad , sorry for the delay. I will continue to maintain this package. I will let you know, If I have fixed the issue

**Comment by robbywh** [comment]
Hello @fernando-ropero-akimad, I have fixed this issue and updated the example code using the newer react-native version. You can try the latest version using this: `yarn add @robbywh/react-native-zendesk-messaging`
